# run a simulation
---
creates: data/results.tsv
depends: src/run_simulation.py
command: 
  - mkdir -p $(dirname {{creates}})
  - python {{depends}} > {{creates}}

# process the results
---
creates: data/x_y.dat
depends: data/results.tsv
command: cut -f1,2 {{depends}} > {{creates}}

# create a figure for the correlation between x and y
---
creates: data/x_y_correlation.png
depends: 
  - src/scatterplot.py
  - data/x_y.dat
command: python {{depends|join(' ')}} {{creates}}

# create a figure to display the distribution of x
---
creates: data/x_pdf.png
depends: 
  - src/pdf.py
  - data/x_y.dat
command: python {{depends|join(' ')}} > {{creates}}

# create a figure to display the distribution of y
---
creates: data/y_pdf.png
depends: 
  - src/pdf.py
  - data/x_y.dat
command: python {{depends|join(' ')}} > {{creates}}

# create a figure for the autocorrelation between consecutive x,y
# pairs
---
creates: data/x_y_autocorrelation.png
depends: 
  - src/autocorrelation.py
  - data/x_y.dat
command: python {{depends|join(' ')}} > {{creates}}
